// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP670xkbbHry7t1G9wSBrMlMj5Y8ZviEw',
    appId: '1:688526544940:web:7122019940201374038189',
    messagingSenderId: '688526544940',
    projectId: 'connectcall-faf16',
    authDomain: 'connectcall-faf16.firebaseapp.com',
    storageBucket: 'connectcall-faf16.firebasestorage.app',
    measurementId: 'G-0ZZRMR3CGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE4xjSqznLTdFfLbGk3kNzEGL1qDxqZus',
    appId: '1:688526544940:android:38c7f64207a9a473038189',
    messagingSenderId: '688526544940',
    projectId: 'connectcall-faf16',
    storageBucket: 'connectcall-faf16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBtvm1xS4LqoP2F-Rs90d6PLLtlpyGeU4',
    appId: '1:688526544940:ios:e222687ee9c636a8038189',
    messagingSenderId: '688526544940',
    projectId: 'connectcall-faf16',
    storageBucket: 'connectcall-faf16.firebasestorage.app',
    iosBundleId: 'com.example.connectCall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBtvm1xS4LqoP2F-Rs90d6PLLtlpyGeU4',
    appId: '1:688526544940:ios:e222687ee9c636a8038189',
    messagingSenderId: '688526544940',
    projectId: 'connectcall-faf16',
    storageBucket: 'connectcall-faf16.firebasestorage.app',
    iosBundleId: 'com.example.connectCall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP670xkbbHry7t1G9wSBrMlMj5Y8ZviEw',
    appId: '1:688526544940:web:ee883c45678ea24f038189',
    messagingSenderId: '688526544940',
    projectId: 'connectcall-faf16',
    authDomain: 'connectcall-faf16.firebaseapp.com',
    storageBucket: 'connectcall-faf16.firebasestorage.app',
    measurementId: 'G-MWG4R0YV6N',
  );
}
